name: Build statistics
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '12 02 * * *'
jobs:
  woocommerce:
    runs-on: ubuntu-latest
    steps:
      - run: brew install cloc
      - uses: actions/checkout@v2
      - run: kotlinc -script script.main.kts -- "https://github.com/woocommerce/woocommerce-android"
        working-directory: script
  wordpress:
    runs-on: ubuntu-latest
    needs: [ woocommerce ]
    steps:
      - run: brew install cloc
      - uses: actions/checkout@v2
      - run: kotlinc -script script.main.kts -- "https://github.com/wordpress-mobile/WordPress-Android"
        working-directory: script
  simplenote:
    runs-on: ubuntu-latest
    needs: [ wordpress ]
    steps:
      - run: brew install cloc
      - uses: actions/checkout@v2
      - run: kotlinc -script script.main.kts -- "https://github.com/Automattic/simplenote-android"
        working-directory: script
  fluxc:
    runs-on: ubuntu-latest
    needs: [ simplenote ]
    steps:
      - run: brew install cloc
      - uses: actions/checkout@v2
      - run: kotlinc -script script.main.kts -- "https://github.com/wordpress-mobile/WordPress-FluxC-Android"
        working-directory: script
  wcstoreapp:
    runs-on: ubuntu-latest
    needs: [ fluxc ]
    steps:
      - run: brew install cloc
      - uses: actions/checkout@v2
      - run: kotlinc -script script.main.kts -- "https://github.com/hichamboushaba/WCStoreApp"
        working-directory: script
  build:
    runs-on: ubuntu-latest
    name: "Build browser site"
    needs: [ wcstoreapp ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
      - name: Distribution
        run: ./gradlew dist
        working-directory: browser
      - name: GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: browser/build/dist
