name: Build statistics
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '12 02 * * *'
jobs:
  woocommerce:
    runs-on: ubuntu-latest
    steps:
      - run: brew install cloc
      - uses: actions/checkout@v2
      - run: kotlinc -script script.main.kts -- "https://github.com/woocommerce/woocommerce-android" "compileWasabiDebugKotlin"
        working-directory: script
      - uses: actions/upload-artifact@v2
        with:
          path: results/woocommerce-android.csv
  wordpress:
    runs-on: ubuntu-latest
    steps:
      - run: brew install cloc
      - uses: actions/checkout@v2
      - run: kotlinc -script script.main.kts -- "https://github.com/wordpress-mobile/WordPress-Android" "compileWordpressWasabiDebugKotlin"
        working-directory: script
      - uses: actions/upload-artifact@v2
        with:
          path: results/WordPress-Android.csv
  simplenote:
    runs-on: ubuntu-latest
    steps:
      - run: brew install cloc
      - uses: actions/checkout@v2
      - run: kotlinc -script script.main.kts -- "https://github.com/Automattic/simplenote-android" "compileDebugKotlin"
        working-directory: script
      - uses: actions/upload-artifact@v2
        with:
          path: results/simplenote-android.csv
  fluxc:
    runs-on: ubuntu-latest
    steps:
      - run: brew install cloc
      - uses: actions/checkout@v2
      - run: kotlinc -script script.main.kts -- "https://github.com/wordpress-mobile/WordPress-FluxC-Android" "compileDebugKotlin"
        working-directory: script
      - uses: actions/upload-artifact@v2
        with:
          path: results/WordPress-FluxC-Android.csv
  wcstoreapp:
    runs-on: ubuntu-latest
    steps:
      - run: brew install cloc
      - uses: actions/checkout@v2
      - run: kotlinc -script script.main.kts -- "https://github.com/hichamboushaba/WCStoreApp" "compileDebugKotlin"
        working-directory: script
      - uses: actions/upload-artifact@v2
        with:
          path: results/WCStoreApp.csv
  build:
    runs-on: ubuntu-latest
    name: "Build browser site"
    needs: [ woocommerce, wordpress, simplenote, fluxc, wcstoreapp ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: results
      - run: mv -v results/artifact/* results
      - run: rm -rf results/artifact
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%d/%m/%y')"
      - name: Push updated statistics to remote
        continue-on-error: true
        run: |
          git diff
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Report update on ${{ steps.date.outputs.date }}"
          git push
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
      - name: Distribution
        run: ./gradlew dist
        working-directory: browser
      - name: GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: browser/build/dist
